### ISSUE TITLE
requirements update

### ISSUE THREAD

**Issue by RMagician** [BobTheBuidler/eth-portfolio#30]
hey there, not being able to install your project, seems the requirements.txt might be out of date ?

**Comment by RMagician** [comment]
```
ERROR: Cannot install -r requirements.txt (line 6) and dank_mids>=4.20.36 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested dank_mids>=4.20.36
    ypricemagic 3.1.2 depends on dank-mids>=4.20.50

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
```
Naturally the next step was to increase the package version of dank_mids to 4.20.50, which results in a PyYaml issue futher down the line.

I've also tried loosing the package requirements, adding certain specific dependencies, and using python 3.10.5.

Unfortunately pip does not seem to be able to resolve the dependencies.

**Comment by RMagician** [comment]
```
 Using cached PyYAML-5.4.1.tar.gz (175 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [48 lines of output]
      running egg_info
      writing lib3\PyYAML.egg-info\PKG-INFO
      writing dependency_links to lib3\PyYAML.egg-info\dependency_links.txt
      writing top-level names to lib3\PyYAML.egg-info\top_level.txt
      Traceback (most recent call last):
        File "C:\Users\mende\Documents\David\programming stuff\eth_portfolio\venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
          main()
        File "C:\Users\mende\Documents\David\programming stuff\eth_portfolio\venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\mende\Documents\David\programming stuff\eth_portfolio\venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\mende\AppData\Local\Temp\pip-build-env-8t3hmcg2\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\mende\AppData\Local\Temp\pip-build-env-8t3hmcg2\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\mende\AppData\Local\Temp\pip-build-env-8t3hmcg2\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 271, in <module>
        File "C:\Users\mende\AppData\Local\Temp\pip-build-env-8t3hmcg2\overlay\Lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\mende\AppData\Local\Temp\pip-build-env-8t3hmcg2\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "C:\Users\mende\AppData\Local\Temp\pip-build-env-8t3hmcg2\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\mende\AppData\Local\Temp\pip-build-env-8t3hmcg2\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\mende\AppData\Local\Temp\pip-build-env-8t3hmcg2\overlay\Lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "C:\Users\mende\AppData\Local\Temp\pip-build-env-8t3hmcg2\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\mende\AppData\Local\Temp\pip-build-env-8t3hmcg2\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 321, in run
          self.find_sources()
        File "C:\Users\mende\AppData\Local\Temp\pip-build-env-8t3hmcg2\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 329, in find_sources
          mm.run()
        File "C:\Users\mende\AppData\Local\Temp\pip-build-env-8t3hmcg2\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 551, in run
          self.add_defaults()
        File "C:\Users\mende\AppData\Local\Temp\pip-build-env-8t3hmcg2\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 589, in add_defaults
          sdist.add_defaults(self)
        File "C:\Users\mende\AppData\Local\Temp\pip-build-env-8t3hmcg2\overlay\Lib\site-packages\setuptools\command\sdist.py", line 112, in add_defaults
          super().add_defaults()
        File "C:\Users\mende\AppData\Local\Temp\pip-build-env-8t3hmcg2\overlay\Lib\site-packages\setuptools\_distutils\command\sdist.py", line 251, in add_defaults
          self._add_defaults_ext()
        File "C:\Users\mende\AppData\Local\Temp\pip-build-env-8t3hmcg2\overlay\Lib\site-packages\setuptools\_distutils\command\sdist.py", line 336, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
        File "<string>", line 201, in get_source_files
        File "C:\Users\mende\AppData\Local\Temp\pip-build-env-8t3hmcg2\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.
```

**Comment by RMagician** [comment]
I tracked the issue down to here:
https://github.com/yaml/pyyaml/issues/724

but even specifying 
```
cython<3.0.0
PyYaml==5.3.1
```
still nothing

**Comment by BobTheBuidler** [comment]
interesting, I have never seen this before. What does your env look like? I have seen the cython/pyyaml thing before, but in a separate project run solely in docker. Are you using docker?

**Comment by BobTheBuidler** [comment]
Oh actually, I just noticed something looking at y our first message. Did you clone the repo or did you install it with pip? If the former, try the latter. This was designed to be uploaded to and installed from pypi, its just not ready for that yet

If you're already in the forked repo you can just `pip install .`

**Comment by RMagician** [comment]
Thanks for the responses :) 

I doesn't look like eth_portfolio, nor eth-portfolio are available through pypi. 
```
ERROR: Could not find a version that satisfies the requirement eth_portfolio (from versions: none)
ERROR: No matching distribution found for eth_portfolio
```
I've also tried running `pip install .` inside the module, with no luck (PyYaml error)

this is all being done through inside a fresh venv, no docker. 

Have you used poetry before ? It tends to do a better job at package dependency management

Manage to mostly resolve my issue:
https://github.com/aws/aws-sam-cli/issues/5543#issuecomment-1638982507
```
pip3 install wheel \
&& pip3 install --no-build-isolation "Cython<3" "pyyaml==5.4.1"
```
probably because can't have cypthon being inside the venv and still working as expected.
Unfortunately there is no way to add that caveat to `requirements.txt`, but maybe you can add it to the readme.

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
referencing 0.32.1 requires attrs>=22.2.0, but you have attrs 22.1.0 which is incompatible.
````
it finally results in this dependency error which maybe come, or not, to affect things
 
however if I now do `pip install .` it sucessfully installs the package so ... :) 

Thank you !

**Comment by RMagician** [comment]
updated readme

https://github.com/BobTheBuidler/eth-portfolio/pull/32

**Comment by BobTheBuidler** [comment]
just do `pip install git+https://github.com/BobTheBuidler/eth-portfolio`

**Comment by BobTheBuidler** [comment]
@RMagician was this helpful?

**Comment by RMagician** [comment]
yes, yes it was thank you :)
