### ISSUE TITLE
brownie network

### ISSUE THREAD

**Issue by RMagician** [BobTheBuidler/eth-portfolio#31]
trying to run:
```
from eth_portfolio import portfolio
from dotenv import load_dotenv

load_dotenv()

block = 19047779
portfolio.eth_balance(block)
```

I get a missing env var
```
INFO: Could not find files for the given pattern(s).
Traceback (most recent call last):
  File "C:\...\eth_portfolio\run.py", line 1, in <module>
    from eth_portfolio import portfolio
  File "C:\...\eth_portfolio\venv\lib\site-packages\eth_portfolio\__init__.py", line 1, in <module>
    from eth_portfolio.portfolio import Portfolio, portfolio
  File "C:\...\eth_portfolio\venv\lib\site-packages\eth_portfolio\portfolio.py", line 13, in <module>
    from y.datatypes import Address, Block
  File "C:\...\eth_portfolio\venv\lib\site-packages\y\__init__.py", line 12, in <module>
    raise NetworkNotSpecified('In order to use pricemagic outside of a brownie project directory, you will need to set $BROWNIE_NETWORK_ID environment variable with the id of your preferred brownie network connection.')
y.NetworkNotSpecified: In order to use pricemagic outside of a brownie project directory, you will need to set $BROWNIE_NETWORK_ID environment variable with the id of your preferred brownie network connection.
```

**Comment by RMagician** [comment]
so I've switched it around,
```
from dotenv import load_dotenv
import os

load_dotenv()
print(os.getenv("BROWNIE_NETWORK_ID"))


from eth_portfolio import portfolio

block = 19047779
portfolio.eth_balance(block)
```

set  `BROWNIE_NETWORK_ID=mainnet`

I now get 
```
$ python run.py
mainnet
INFO: Could not find files for the given pattern(s).
Traceback (most recent call last):
  File "C:\Users\mende\Documents\David\programming stuff\eth_portfolio\run.py", line 8, in <module>
    from eth_portfolio import portfolio
  File "C:\Users\mende\Documents\David\programming stuff\eth_portfolio\venv\lib\site-packages\eth_portfolio\__init__.py", line 1, in <module>
    from eth_portfolio.portfolio import Portfolio, portfolio
  File "C:\Users\mende\Documents\David\programming stuff\eth_portfolio\venv\lib\site-packages\eth_portfolio\portfolio.py", line 13, in <module>
    from y.datatypes import Address, Block
  File "C:\Users\mende\Documents\David\programming stuff\eth_portfolio\venv\lib\site-packages\y\__init__.py", line 13, in <module>        
    network.connect(os.environ['BROWNIE_NETWORK_ID'])
  File "C:\Users\mende\Documents\David\programming stuff\eth_portfolio\venv\lib\site-packages\brownie\network\main.py", line 40, in connect
    web3.connect(host, active.get("timeout", 30))
  File "C:\Users\mende\Documents\David\programming stuff\eth_portfolio\venv\lib\site-packages\brownie\network\web3.py", line 54, in connect
    uri = _expand_environment_vars(uri)
  File "C:\Users\mende\Documents\David\programming stuff\eth_portfolio\venv\lib\site-packages\brownie\network\web3.py", line 185, in _expand_environment_vars
    raise ValueError(f"Unable to expand environment variable in host setting: '{uri}'")
ValueError: Unable to expand environment variable in host setting: 'https://mainnet.infura.io/v3/$WEB3_INFURA_PROJECT_ID'
```
